### ISSUE TITLE
No source data found

### ISSUE THREAD

**Issue by acka47** [hbz/mabxml-elasticsearch#11]
I met a data where the source data is missing: http://lobid.org/resource/ZDB2232704-6/about

**Comment by fsteeg** [comment]
I think this is true for many (all?) ZDB resources.

**Comment by dr0i** [comment]
Right! Follow the sameAs to the HT resource.

**Comment by acka47** [comment]
> Right! Follow the sameAs to the HT resource.

...and then I get the RDF for the ZDB resource without source data.

**Comment by dr0i** [comment]
Seems to be an issue with the API:
Putting 'http://lobid.org/resource/HT014720195' into the browser brings up the metadata about the ZDB resource.
As both graphs (HT and ZDB) are sameAs AND they are correctly subsumed under the '@graph' node I would suggest to search for the non-ZDB resources when using the 'source' button.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/resource/ZDB2232704-6

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/resource/ZDB2232704-6
http://lobid.org/resource/ZDB2232704-6?format=source
