### ISSUE TITLE
Set up separate staging and production instances

### ISSUE THREAD

**Issue by fsteeg** [hbz/mabxml-elasticsearch#14]
While the service is beta, it is used in lobid production for the source tab. This results in downtimes during redeployment and in breaking our release management with initial deployments to staging and functional review (see https://github.com/hbz/lobid/issues/251).

**Comment by fsteeg** [comment]
I've set up a staging system in `sol@quaoar1:~/git/mabxml-elasticsearch-staging/web`, added both mabxml-elasticsearch (port 7300) and mabxml-elasticsearch-staging (port 7301) to `/etc/monit/conf.d/play-instances.rc` and set up the proxy for http://test.lobid.org/hbz01.

@dr0i, `monit status` looks good, but assigning you for review of monit config on quaoar1.

**Comment by dr0i** [comment]
Looks good, starts automatically after killing.
