### ISSUE TITLE
Resources that don't exist yield errors

### ISSUE THREAD

**Issue by fsteeg** [hbz/mabxml-elasticsearch#16]
e.g. http://beta.lobid.org/hbz01/HT01858183

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/hbz01/HT01858183X (404)
http://test.lobid.org/hbz01/HT017665866 (200)

**Comment by acka47** [comment]
+1 BTW, couldn't we omit the "beta" by now?

**Comment by fsteeg** [comment]
Deployed to production and set up non-beta proxy:

http://lobid.org/hbz01/HT01858183X (404)
http://lobid.org/hbz01/HT017665866 (200)

And beta-redirects. See:

http://beta.lobid.org/hbz01/HT01858183X (404)
http://beta.lobid.org/hbz01/HT017665866 (200)
