### ISSUE TITLE
Move transformation into Play project

### ISSUE THREAD

**Issue by fsteeg** [hbz/mabxml-elasticsearch#26]
To get one project and one build, like in lobid-organisations

**Comment by fsteeg** [comment]
Deployed to staging at `sol@quaoar1:~/git/mabxml-elasticsearch-staging`. Updated and reloaded `mabxml-elasticsearch-staging` monit setup in `/etc/monit/conf.d/play-instances.rc`. Set up cron job in `sol@quaoar1`'s crontab for `mabxml-elasticsearch-staging` to use same repo as the web app.

Running at http://test.lobid.org/hbz01

**Comment by dr0i** [comment]
+1
