### ISSUE TITLE
Remove OAI-PMH elements from responses

### ISSUE THREAD

**Issue by fsteeg** [hbz/mabxml-elasticsearch#48]
Originally our `hbz01` URLs serving mabxml were only intended for internal debugging, so we simply took our export data as it was and exposed it. But actually the OAI-PMH elements (`OAI-PMH`, `ListRecords` etc.) make no sense in the context of single resources like http://lobid.org/hbz01/HT000052997

I think we should only serve the `OAI-PMH / ListRecords / record / metadata / record` element.

I suggest that we clean this up after announcing it on the list with some time for people to adapt.

**Comment by dr0i** [comment]
The OAI-PMH elements make indeed no sense. ExLibris did this all wrong.
But: if you change the structural consistence now most (all?) processing programs trained on the bad original structure will break.
@fsteeg is there any real need to change the structure?

**Comment by fsteeg** [comment]
There is no rush, so we could announce it with some generous time (6 months?), but I think we should fix this at some point.

**Comment by fsteeg** [comment]
We could implement the new format as a route under `resources` (like we do for deletions), so something like `resources/hbz01/` (or some other name if that makes sense, like `resources/mabxml/`) and leave the current format running for a while.

**Comment by dr0i** [comment]
Again, I advice against it. It's the original "aleph MAB XML", used by others e.g. in Austrian, and no need to invent another structure and break any process routine.
Also, Aleph is going to be replaced, thus Aleph-Mab-Xml.

**Comment by acka47** [comment]
Let's discuss this on a Thursday when everybody is in the office.

**Comment by fsteeg** [comment]
We decided to leave it as it is, for consistency with published dumps and simplicity. Closing.
