### ISSUE TITLE
Updates failing

### ISSUE THREAD

**Issue by dr0i** [hbz/mabxml-elasticsearch#58]
from the `logs/application.log`:

>Transformation failed
org.metafacture.framework.MetafactureException: java.io.EOFException

It's likely a corrupted update tar gz. Going to just skip this and take the next one.

**Comment by dr0i** [comment]
This is the file:
> ls -ahl
[...] 424371753 Aug  6 03:15 DE-605-aleph-update-marcxchange-20220805-20220806.tar.gz

**Comment by dr0i** [comment]
Kudos  @blackwinter !
Because the updates were really big this week there was a race condition in the workflow, resulting in copying  unfinished archives and thus the `EOFException`.
Going to copy the complete files and restarting update.

**Comment by dr0i** [comment]
Works. Closing.

**Comment by dr0i** [comment]
@TobiasNx [asked](https://github.com/hbz/lobid-resources/issues/1358#issuecomment-1216582007):

> Is still a problem? http://lobid.org/hbz01/HT021429811 The MAB file is not accessable?

Investigating ...

**Comment by dr0i** [comment]
Not sure what caused the problem.
I did:
```
 scp /data/DE-605/mabxml/update/DE-605-aleph-update-marcxchange-2022080[56789]* $servername:/data/DE-605/mabxml/updates/
``` 
i.e. all files in question, but somehow not all data was indexed :(

 Going to index the files step by step:
- [ ] DE-605-aleph-update-marcxchange-20220804-20220805.tar.gz
- [ ] DE-605-aleph-update-marcxchange-20220808-20220809.tar.gz
- [ ] DE-605-aleph-update-marcxchange-20220809-20220810.tar.gz
- [ ] DE-605-aleph-update-marcxchange-20220810-20220811.tar.gz

**Comment by dr0i** [comment]
I have to admit, I don't know how this works:
while the logs are still written to `logs/processMabxml.sh.20220818-weywot.log` with content 
> Transformed: dir=/data/DE-605/mabxml/updates, suffix=gz,

the file in /data/DE-605/mabxml/updates` was removed 20 minutes ago. Is it somehow cached? It wasn't moved somewhere obviously, i.e. somewhere in the tree of the root of the repo.

**Comment by dr0i** [comment]
However this works ;)
... copying `DE-605-aleph-update-marcxchange-2022080[56789]*` are missing `DE-605-aleph-update-marcxchange-20220810-20220811.tar.gz` , and this is the file where `HT021429811` is part of. So I guess I just forgot to copy that file. Will do this now and look tomorrow.

**Comment by dr0i** [comment]
Ack that  http://lobid.org/hbz01/HT021429811 is ok now.
@TobiasNx please check.

**Comment by TobiasNx** [comment]
> Ack that http://lobid.org/hbz01/HT021429811 is ok now. @TobiasNx please check.

+1 seems to work now.

**Comment by dr0i** [comment]
Closing.
